name: Release library

on:
  release:
    types: [ published ]

env:
  # Gradle GPG Keys
  GRADLE_GPG_SIGN_KEY: ${{ secrets.GRADLE_GPG_SIGN_KEY }}
  GRADLE_GPG_SIGN_PASSWORD: ${{ secrets.GRADLE_GPG_SIGN_PASSWORD }}

  # Sonatype
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./hubspot

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./hubspot

      - name: Publish library
        run: ./gradlew publish
        working-directory: ./hubspot
